services:
  db:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: aspteam
      POSTGRES_PASSWORD: asp20252026
      POSTGRES_DB: forecastdb
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - app-net

  model-service:
    build: ./model-service
    container_name: flask-model
    ports:
      - "5000:5000"
    networks:
      - app-net

  backend:
    build: ./
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - model-service
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db:
