services:
  db:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: aspteam
      POSTGRES_PASSWORD: asp20252026
      POSTGRES_DB: forecastdb
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5332:5432"
    networks:
      - app-net

  model-service:
    build: ./model-service
    container_name: model-service
    ports:
      - "5000:5000"
    networks:
      - app-net

  fetch-service:
    build: ./fetch-service
    container_name: fetch-service
    environment:
      - DATABASE_URL=postgresql://aspteam:asp20252026@db:5432/forecastdb
    depends_on:
      - db
    networks:
      - app-net
    ports:
      - "5500:5500"

  backend:
    build: ./
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - model-service
      - fetch-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db:
