# === Docker Container Profile ===

spring.datasource.url=jdbc:postgresql://postgres-spring-boot:5432/forecastdb
spring.datasource.username=aspteam
spring.datasource.password=asp20252026
model.service.url=http://flask-model:5000/predict
