# === Local Development Profile ===

spring.datasource.url=jdbc:postgresql://localhost:5332/forecastdb
spring.datasource.username=aspteam
spring.datasource.password=asp20252026

model.service.url=http://localhost:5000
fetch.service.url=http://localhost:5500