# === Docker Container Profile ===

spring.datasource.url=jdbc:postgresql://db:5432/forecastdb
spring.datasource.username=aspteam
spring.datasource.password=asp20252026

model.service.url=http://model-service:5000/predict
fetch.service.url=http://fetch-service:5500/latest